---
inputs:
- type: git
  branch: multi-repo-1
  service: ${GIT_REPO}
  path: .tekton
- type: git
  branch: multi-repo-2
  service: ${GIT_REPO}
  path: .tekton
triggers:
- type: git
  name: Git PR Trigger
  service: ${GIT_REPO}
  branch: master
  events: {"push":true,"pull_request":true,"pull_request_closed":false}
  eventListener: listener
- type: manual
  name: Manual Trigger
  eventListener: listener
  disabled: "true"
properties:
- name: apikey
  value: ${API_KEY}
  type: SECURE
- name: cluster
  value: ${PROD_CLUSTER_NAME}
  type: text 
- name: registryNamespace
  value: ${REGISTRY_NAMESPACE}
  type: text 
- name: clusterNamespace
  value: ${PROD_CLUSTER_NAMESPACE}
  type: text
- name: clusterRegion
  value: ${PROD_REGION_ID}
  type: text
- name: registryRegion
  value: ${REGISTRY_REGION_ID}
  type: text
- name: repository
  value: ${REPOSITORY}
  type: text
- name: revision
  value: ${REVISION}
  type: text
- name: region
  value: ${REGION}
  type: SINGLE_SELECT
